### ISSUE TITLE
iOS 运行之后 点击按钮没有反应 出现以下报错

### ISSUE THREAD

**Issue by WHLwhlww** [ethand91/mediasoup-ios-client#26] opened 2020-05-14 06:39 UTC
@ethand91 objc[4211]: Class RTCAudioSessionDelegateAdapter is implemented in both /private/var/containers/Bundle/Application/62D8A3B1-DE3F-4834-B559-2700962BA893/mediasoup-ios-cient-sample.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x101b4d590) and /private/var/containers/Bundle/Application/62D8A3B1-DE3F-4834-B559-2700962BA893/mediasoup-ios-cient-sample.app/Frameworks/WebRTC.framework/WebRTC (0x101439200). One of the two will be used. Which one is undefined.

**Comment by ethand91** [comment] 2020-05-14 09:59
duplicate of https://github.com/ethand91/mediasoup-ios-client/issues/9

**Closed as completed by ethand91** 2020-05-14 09:59 UTC

**Comment by WHLwhlww** [comment] 2020-05-15 07:48
After IOS runs, clicking the button does not respond to the following error
