### ISSUE TITLE
WebRTC framework implemented twice

### ISSUE THREAD

**Issue by mschonvogel** [ethand91/mediasoup-ios-client#9] opened 2020-03-02 14:54 UTC
```
objc[24967]: Class RTCAudioSessionDelegateAdapter is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729b858) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c234d8). One of the two will be used. Which one is undefined.
objc[24967]: Class DeviceInfoIosObjC is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729bc68) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23528). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCVideoCaptureIosObjC is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729bcb8) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23578). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCAudioSession is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729b8a8) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c235c8). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCAudioSessionConfiguration is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729b8f8) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23618). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCNativeAudioSessionDelegateAdapter is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729b948) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23668). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCEncodedImage is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729b9c0) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c236e0). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCRtpFragmentationHeader is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729ba10) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23730). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCVideoCapturer is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729ba38) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23758). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCVideoCodecInfo is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729ba88) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c237a8). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCVideoEncoderQpThresholds is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729bad8) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c237f8). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCVideoEncoderSettings is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729bb50) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23870). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCVideoFrame is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729bb78) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c23898). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCDispatcher is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729bbf0) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c249a0). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCCameraPreviewView is implemented in both /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/mediasoup_client_ios.framework/mediasoup_client_ios (0x10729bc18) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c249c8). One of the two will be used. Which one is undefined.
objc[24967]: Class RTCCVPixelBuffer is implemented in both /System/Library/PrivateFrameworks/WebCore.framework/Frameworks/libwebrtc.dylib (0x20c5a09a0) and /private/var/containers/Bundle/Application/DB88FAAB-AF8E-405A-92A6-9C54F9B3EC55/Fuu.app/Frameworks/WebRTC.framework/WebRTC (0x106c24ab8). One of the two will be used. Which one is undefined.
```

**Comment by ethand91** [comment] 2020-03-03 00:51
Will look into it.

**Comment by mschonvogel** [comment] 2020-03-03 09:35
Thank you so much

**Comment by WHLwhlww** [comment] 2020-05-14 09:38
Hello,，same problem， have you solved your problem? help me，thankyou ！

**Comment by ethand91** [comment] 2020-07-14 05:20
This is just a warning and should not interfere with the application, I don't think this can be fixed without an update to the WebRTC library or an iOS update.

**Comment by ethand91** [comment] 2020-07-16 00:56
Closing for now.

**Closed as completed by ethand91** 2020-07-16 00:56 UTC
Labels: enhancement, help wanted

**Comment by SimonPickup** [comment] 2021-04-14 04:23
I suspect that I have a problem caused by this - different paths are accessing different instances of global RTCAudioSessionConfiguration default config.

> This is just a warning and should not interfere with the application, I don't think this can be fixed without an update to the WebRTC library or an iOS update.

Can you please elaborate further on why you think this cannot be fixed without WebRTC or iOS change?
